version: "3.5"

services:

  traefik:
    image: "traefik:v2.9"
    container_name: "traefik"
    restart: always
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entryPoints.web-secure.address=:84"
    ports:
      - "8888:80"
      - "8884:84"
      - "8880:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - api-gateway

networks:
  api-gateway:
    name: gateway